# Generated by Django 4.0.6 on 2022-07-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operand1', models.IntegerField(max_length=100)),
                ('operand2', models.IntegerField(max_length=100)),
                ('operator', models.CharField(max_length=10)),
                ('result', models.IntegerField(max_length=100)),
            ],
            options={
                'db_table': 'input',
            },
        ),
    ]
