# Generated by Django 4.0.6 on 2022-07-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_remove_input_operand1_remove_input_operand2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calcy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'calcy',
            },
        ),
    ]
