# Generated by Django 4.0.6 on 2022-07-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_calcy'),
    ]

    operations = [
        migrations.AddField(
            model_name='calcy',
            name='expression',
            field=models.CharField(default='empty', max_length=300),
        ),
    ]
